service: sunwell-lambda

provider:
  name: aws
  runtime: "nodejs6.10"
  memorySize: 128
  timeout: 15
  deploymentBucket:
    name: hearthsim-lambda-artifacts

package:
  include:
    - "*.so.0"
    - "hs-fonts/*/*.ttf"
    - "cards.json"

functions:
  render:
    handler: index.handler

    events:
      - http:
          path: render
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - "image/png"
